spring.cloud.config.profile=dev
spring.application.name=GestVuelos-ms

server.port=0
#Definimos un id autogenerado para las instancias del MS
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
