spring.application.name=Api-gateway
# esta anotacion habilita el cliente de discoveryclient
spring.cloud.gateway.discovery.locator.enabled=true
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

spring.cloud.loadbalancer.ribbon.enabled=false

#Lista de MS registrados ENRUTADO
#====================================
spring.cloud.gateway.routes[0].id=GestVuelos-ms
spring.cloud.gateway.routes[0].uri=lb://GESTVUELOS-MS
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/categories/**, /api/vuelos/**

spring.cloud.gateway.routes[1].id=Reservas-ms
spring.cloud.gateway.routes[1].uri=lb://RESERVAS-MS
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/reservas/**

spring.cloud.gateway.routes[2].id=Notificaciones-ms
spring.cloud.gateway.routes[2].uri=lb://NOTIFICACIONES-MS
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/notificaciones/**

spring.cloud.gateway.routes[3].id=Usuarios-ms
spring.cloud.gateway.routes[3].uri=lb://USUARIOS-MS
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/usuarios/**

spring.cloud.gateway.routes[4].id=GestHoteles-ms
spring.cloud.gateway.routes[4].uri=lb://GESTHOTELES-MS
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/hoteles/**

# KEYCLOCK

spring.cloud.gateway.default-filters=TokenRelay

# ===== OAUTH2 CLIENT (Keycloak) =====
# Proveedor (Issuer)
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9090/realms/JAO_REALM

# Registro de cliente: JAO_CLIENT (este es el nombre que Keycloak debe tener como client_id)
spring.security.oauth2.client.registration.JAO_CLIENT.client-id=JAO_CLIENT
spring.security.oauth2.client.registration.JAO_CLIENT.client-secret=vrTT3ZA6AnfliVsHTQcwuK6I1kFhL7sH
spring.security.oauth2.client.registration.JAO_CLIENT.provider=keycloak
spring.security.oauth2.client.registration.JAO_CLIENT.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.JAO_CLIENT.redirect-uri=http://localhost:8080/login/oauth2/code/JAO_CLIENT
spring.security.oauth2.client.registration.JAO_CLIENT.scope=openid
# Proveedor
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9090/realms/jao-booking-ms-realm
#
## Registro de cliente
#spring.security.oauth2.client.registration.spring-cloud-gateway-client.client-id=spring-cloud-gateway-client
#spring.security.oauth2.client.registration.spring-cloud-gateway-client.client-secret=ohHwBcmVsSJAV4NmS86ohPOY2nKiyJ5J
#spring.security.oauth2.client.registration.spring-cloud-gateway-client.provider=keycloak
#spring.security.oauth2.client.registration.spring-cloud-gateway-client.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.spring-cloud-gateway-client.redirect-uri=http://localhost:8080/login/oauth2/code/spring-cloud-gateway-client


# Configuracion para Resource Server JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/JAO_REALM
#Habilitar logs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG