spring.cloud.config.profile=dev
# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# === DATOS DE CONEXIoN A MYSQL (desde Docker Compose) ===

spring.datasource.url=jdbc:mysql://localhost:3306/login_auth_db
spring.datasource.username=login_auth_user
spring.datasource.password=login_auth_pass
# ===============================
# KEYCLOAK CONFIG
# ===============================
keycloak.auth-server-url=localhost:9092
keycloak.realm=http://localhost:9090/realms/JAO_REALM
keycloak.resource=JAO_CLIENT
keycloak.credentials.secret=hvs.FoWUtuIn0lL2KB5ZwPlSPRqc


