global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'usuarios-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:61194']

  - job_name: 'GestHoteles-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:61195']

  - job_name: 'GestVuelos-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:61196']

  - job_name: 'Notificaciones-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:61197']

  - job_name: 'pagos-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:61199']

  - job_name: 'Reservas-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:61200']
	  
  - job_name: 'AlquilerVehiculos-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:61201']
