version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: reservas_db
      MYSQL_USER: reservas_user
      MYSQL_PASSWORD: reservas_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - reservas-network

volumes:
  mysql_data:

networks:
  reservas-network:
    driver: bridge
