booking.property= Alquiler Vehiculos profile DEV

app.testProp=Property of test UPDATED for Bus and Message Broker
app.testPropVersion=Version 001

# Configuración R2DBC para MySQL (usando R2DBC driver adecuado)
spring.r2dbc.url=r2dbc:mysql://localhost:3312/alquilervehiculos_db
spring.r2dbc.username=alquiler_user
spring.r2dbc.password=alquiler_pass

# Otros parámetros si aplican
spring.sql.init.mode=always

# Si usas Flyway o Liquibase para migraciones, configura aquí

# Desactiva JPA (no se debe usar con WebFlux/reactivo)
spring.jpa.hibernate.ddl-auto=none

# === JPA / Hibernate ===
# spring.sql.init.mode=always
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.generate-ddl=true

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
