booking.property= Hoteles profile DEV

app.testProp=Property of test UPDATED for Bus and Message Broker
app.testPropVersion=Version 001

# === JPA / Hibernate ===
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
#spring.datasource.url=bc:mysql://localhost:3311/gestHoteles_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect