spring.application.name=Config-server
server.port=8888
#spring.cloud.config.server.git.uri=https://github.com/jaoprogramador/workspaceMSBookingJAO/tree/microserviciosConfigDiscovery1/Service-configuration
# spring.cloud.config.server.git.uri=https://github.com/jaoprogramador/workspaceMSBookingJAO/microserviciosConfigDiscovery1/Service-configuration
# 1) URI .git del repositorio (sin /tree, sin /branch, sin /carpeta)
spring.cloud.config.server.git.uri=https://github.com/jaoprogramador/workspaceMSBookingJAO.git

# 2) La rama por defecto que quiere clonar (default-label)
#spring.cloud.config.server.git.default-label=microserviciosConfigDiscovery1
spring.cloud.config.server.git.default-label=release_Usuarios_GestHoteles20250730

# 3) Si tus archivos estan dentro de un subdirectorio, ponlo aqui
spring.cloud.config.server.git.searchPaths=Service-configuration

spring.cloud.config.server.git.clone-on-start=true