spring.application.name=AlquilVehiculos-ms
spring.cloud.config.profile=dev

#spring.r2dbc.url= r2dbc:mysql://localhost:3312/alquilervehiculos_db
#spring.r2dbc.username= alquiler_user
#spring.r2dbc.password= alquiler_pass
# QUITAR 
#spring.cloud.vault.enabled=false
#spring.cloud.config.enabled=false

