version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db-gestHoteles
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: gestHoteles_db
      MYSQL_USER: gestHoteles_user
      MYSQL_PASSWORD: gestHoteles_pass
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gestHoteles-network

volumes:
  mysql_data:

networks:
  gestHoteles-network:
    driver: bridge
